#pragma once
#include "Elaine.h"
#include "ElaineCoreMacroDefinition.h"
#include "ElaineCorePrerequirements.h"
#include "ElaineStdRequirements.h"
#include "ElaineSingleton.h"
#include "ElaineThread.h"
#include "ElaineThreadManager.h"
#include "math/ElaineMath.h"
#include "math/ElaineMatrix3.h"
#include "math/ElaineMatrix4.h"
#include "math/ElaineQuaternion.h"
#include "math/ElaineVector2.h"
#include "math/ElaineVector3.h"
#include "math/ElaineVector4.h"
#include "math/ElaineRandom.h"
#include "math/ElaineTransform.h"
#include "ElaineFileSystem.h"
#include "ElaineHash.h"
#include "ElaineRoot.h"
#include "ElaineLogSystem.h"
#include "ElaineSceneNode.h"
#include "ElaineUseCount.h"
#include "JobSystem/ElaineJob.h"
#include "JobSystem/ElaineJobSystem.h"
#include "ElaineResourceBase.h"
#include "ElaineResourceManager.h"
#include "common/ElaineRHI.h"
#include "ElaineRenderSystem.h"
#include "vulkan/ElaineVulkanRHI.h"
#include "ElaineCamera.h"
#include "ElaineEntity.h"
#include "ElaineMemory.h"
#include "ElaineTimer.h"
#include "ElaineName.h"
#include "ElaineStringUtils.h"
#include "nlohmann/json.hpp"

namespace Elaine
{

}