#pragma once
#include "Elaine.h"
#include "ElaineCoreMacroDefinition.h"
#include "ElaineCorePrerequirements.h"
#include "ElaineStdRequirements.h"
#include "ElaineSingleton.h"
#include "ElaineThread.h"
#include "ElaineThreadManager.h"
#include "math/ElaineMath.h"
#include "math/ElaineMatrix3.h"
#include "math/ElaineMatrix4.h"
#include "math/ElaineQuaternion.h"
#include "math/ElaineVector2.h"
#include "math/ElaineVector3.h"
#include "math/ElaineVector4.h"
#include "math/ElaineRandom.h"
#include "math/ElaineTransform.h"
#include "ElaineSingleton.h"
#include "ElaineFileSystem.h"
#include "ElaineHash.h"
#include "ElaineRoot.h"
#include "cJSON.h"
#include "ElaineLogSystem.h"
#include "ElaineSceneNode.h"
#include "ElaineUseCount.h"
#include "component/ElaineGameObject.h"
#include "JobSystem/ElaineJob.h"
#include "JobSystem/ElaineJobSystem.h"
#include "component/ElaineComponentFactory.h"
#include "resource/ElaineResourceBase.h"
#include "resource/ElaineResourceManager.h"
#include "resource/ElaineGameObjectInfoMgr.h"
#include "component/ElaineComponent.h"
#include "render/common/ElaineRHI.h"
#include "render/dx12/ElaineDX12RHI.h"
#include "render/ElaineRenderSystem.h"
#include "render/vulkan/ElaineVulkanRHI.h"
#include "ElaineCamera.h"
#include "render/ElaineEntity.h"
#include "ElaineMemory.h"
#include "ElaineTimer.h"

namespace Elaine
{

}