#pragma once
#include "VirtualTexture/ElaineVirtualTextureTypes.h"
#include "Common/ElaineCorePrerequirements.h"

namespace Elaine
{
	class VirtualTextureSpace;
	class PhysicalTilePool;
	class RHITexture;
	class SceneManager;

	//=========================================================================
	// RVT Tile Render Request
	//=========================================================================
	/**
	 * Describes a tile that needs to be rendered for the RVT.
	 * Consumed by RVTTileRenderer to produce tile content.
	 */
	struct RVTTileRenderRequest
	{
		VTTileCoord Coord;                // Which tile to render
		PhysicalTileLocation PhysTarget;  // Where to upload the result in the physical atlas

		// World-space AABB covered by this tile
		float WorldMinX = 0.0f;
		float WorldMinY = 0.0f;
		float WorldMaxX = 0.0f;
		float WorldMaxY = 0.0f;

		uint32 FrameRequested = 0;
		ETilePriority Priority = ETilePriority::Medium;

		bool operator<(const RVTTileRenderRequest& Other) const
		{
			return Priority < Other.Priority;
		}
	};

	//=========================================================================
	// RuntimeVirtualTexture
	//=========================================================================
	/**
	 * Runtime Virtual Texture (RVT) - tiles are rendered on demand rather
	 * than loaded from disk.
	 *
	 * Key differences from SVT:
	 *   - Tile content is generated by rendering the scene from top-down
	 *     orthographic projection into a tile-sized render target
	 *   - Content changes when the scene changes (dynamic)
	 *   - Supports invalidation of dirty regions
	 *   - Typically used for landscape blending, decal projection, etc.
	 *
	 * Flow per frame:
	 *   1. Feedback analysis identifies needed tiles (same as SVT)
	 *   2. Instead of disk I/O, tiles are rendered via RVTTileRenderer
	 *   3. Rendered tiles are copied to the physical atlas
	 *   4. Page table and indirection texture are updated (same as SVT)
	 */
	class ElaineCoreExport RuntimeVirtualTexture : public IVirtualTexture
	{
	public:
		/**
		 * Create an RVT with the given world-space bounds and resolution.
		 *
		 * @param InDesc - Space descriptor (VirtualSize, WorldBounds, Layers, etc.)
		 * @param InSceneManager - Scene used for tile rendering
		 */
		RuntimeVirtualTexture(const VTSpaceDesc& InDesc, SceneManager* InSceneManager);
		virtual ~RuntimeVirtualTexture();

		//=====================================================================
		// IVirtualTexture Implementation
		//=====================================================================
		const VTSpaceDesc& GetSpaceDesc() const override { return mDesc; }
		uint8 GetSpaceID() const override { return mSpaceID; }
		EVirtualTextureType GetType() const override { return EVirtualTextureType::RVT; }
		void Update(uint32 FrameNumber) override;
		bool IsTileResident(const VTTileCoord& Coord) const override;
		RHITexture* GetIndirectionTexture() const override;
		RHITexture* GetPhysicalAtlasTexture(uint8 LayerIndex) const override;
		VTStatistics GetStatistics() const override;

		//=====================================================================
		// RVT-Specific Interface
		//=====================================================================

		/** Initialize and register with the VT system */
		void Initialize();

		/** Shutdown and unregister */
		void Shutdown();

		/** Get the scene manager used for tile rendering */
		SceneManager* GetSceneManager() const { return mSceneManager; }

		//---------------------------------------------------------------------
		// World-Space Mapping
		//---------------------------------------------------------------------

		/** Get world-space bounds */
		void GetWorldBounds(float& OutMinX, float& OutMinY, float& OutMaxX, float& OutMaxY) const;

		/** Set world-space bounds (triggers full invalidation) */
		void SetWorldBounds(float MinX, float MinY, float MaxX, float MaxY);

		/** Convert world position to virtual UV [0,1] */
		void WorldToVirtualUV(float WorldX, float WorldY, float& OutU, float& OutV) const;

		/** Get the world-space AABB for a specific tile */
		void GetTileWorldBounds(const VTTileCoord& Coord,
			float& OutMinX, float& OutMinY, float& OutMaxX, float& OutMaxY) const;

		/**
		 * Compute the orthographic projection matrix for rendering a tile.
		 * Projects the world-space AABB of the tile onto a TileSize x TileSize viewport.
		 *
		 * @param Coord - Tile coordinate
		 * @param OutView - Output view matrix (top-down, Y-up)
		 * @param OutProj - Output orthographic projection matrix
		 */
		void ComputeTileProjection(const VTTileCoord& Coord,
			float* OutViewMatrix4x4, float* OutProjMatrix4x4) const;

		//---------------------------------------------------------------------
		// Invalidation
		//---------------------------------------------------------------------

		/** Invalidate a world-space region (marks overlapping tiles as dirty) */
		void InvalidateWorldRegion(float MinX, float MinY, float MaxX, float MaxY);

		/** Invalidate all tiles (full rebuild) */
		void InvalidateAll();

		/** Get the list of tiles that need to be re-rendered */
		const std::vector<RVTTileRenderRequest>& GetPendingRenderRequests() const { return mPendingRenders; }

		/** Clear pending render requests after they've been processed */
		void ClearPendingRenderRequests();

		/** Called by the RVT tile renderer when a tile has been rendered and uploaded */
		void OnTileRenderComplete(const VTTileCoord& Coord, const PhysicalTileLocation& Location);

		//---------------------------------------------------------------------
		// Tile Request Processing (called by VT System)
		//---------------------------------------------------------------------

		/**
		 * Process tile requests from feedback analysis.
		 * Instead of loading from disk, this creates RVTTileRenderRequests.
		 */
		void ProcessTileRequest(const VTTileRequest& Request);

	private:
		/** Convert world-space region to tile coordinate range at a given mip */
		void WorldRegionToTileRange(float MinX, float MinY, float MaxX, float MaxY,
			uint8 MipLevel, uint16& OutTileMinX, uint16& OutTileMinY,
			uint16& OutTileMaxX, uint16& OutTileMaxY) const;

	private:
		VTSpaceDesc mDesc;
		uint8 mSpaceID = 0;
		bool mInitialized = false;

		// Scene used for rendering tiles
		SceneManager* mSceneManager = nullptr;

		// Pending tile render requests (consumed by RVTTileRenderer)
		std::vector<RVTTileRenderRequest> mPendingRenders;

		// Set of dirty tile coordinates that need re-rendering
		std::unordered_set<uint32> mDirtyTiles; // packed VTTileCoord

		// Maximum number of tiles to render per frame (budget)
		uint32 mMaxTileRendersPerFrame = 16;

		// Statistics
		uint32 mTotalTilesRendered = 0;
	};

} // namespace Elaine
